---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ ssh_private_key | dirname }}"
    state: directory
    mode: '0700'

- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: "{{ ssh_private_key }}"
    type: ed25519
  register: ssh_keygen
