---
- name: Set-up VMs on a KVM
  hosts: localhost
  vars_files:
    - "{{ nodes_file | default('../vars/nodes.yml') }}"
  roles:
    - role: vm_init
      tags: init
    - role: vm_destroy
      tags: destroy

- name: Provision the cluster
  hosts: k8s_cluster
  become: true
  roles:
    - role: vm_provision
      tags: provision
