ingress:
  enabled: true
  hosts:
    - host: gopher.naquadah.alak
      paths:
        - path: /
          pathType: Prefix
hpa:
  enabled: true
serviceMonitor:
  enabled: true
replicaCount: 3
image:
  tag: sha-9addb3f934fff05286e96c72f5b9a1fde15d1001
