ingress:
  enabled: true
  hosts:
    - host: gopher.naquadah.alak
      paths:
        - path: /
          pathType: Prefix
hpa:
  enabled: true
serviceMonitor:
  enabled: true
prometheusRule:
  enabled: true
alertmanagerConfig:
  enabled: true
replicaCount: 3
image:
  tag: sha-7a96421fa9f5ba0aceec4214635088c9c3ab823f
