ingress:
  enabled: true
  hosts:
    - host: gopher.naquadah.alak
      paths:
        - path: /
          pathType: Prefix
hpa:
  enabled: true
serviceMonitor:
  enabled: true
replicaCount: 3
image:
  tag: sha-77f70f65ea9107b8884b89f77b09a0f5712680c9
