---
- name: Undefine the VMs
  community.libvirt.virt:
    uri: "{{ uri }}"
    command: undefine
    name: "{{ node.name }}"
    flags:
      - delete_volumes
  loop: "{{ nodes }}"
  loop_control:
    loop_var: node
