{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gopher.fullname" . }}
  labels:
    {{- include "gopher.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gopher.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.portName | default "http" }}
{{- end }}
