services:
  reverse-proxy:
    depends_on:
      application:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 128M
        reservations:
          cpus: 0.1
          memory: 32M
    image: docker.io/library/nginx:1.29.6-alpine
    networks:
      api:
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - ./nginx/docker.dost.edu.az.conf:/etc/nginx/conf.d/docker.dost.edu.az.conf:ro
      - ./logs/nginx:/var/log/nginx

  application:
    build: php-fpm
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M
    entrypoint:
      - /entrypoint.sh
    env_file: ./php-fpm.env
    healthcheck:
      test:
        - CMD-SHELL
        - |
          SCRIPT_FILENAME=/var/www/html/index.php
          REQUEST_METHOD=GET
          REQUEST_URI=/api/health
          cgi-fcgi -bind -connect 127.0.0.1:9000 ||
          exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      api:
      db:
    restart: unless-stopped
    secrets:
      - mysql-dostdev
    volumes:
      - ./php-fpm/html:/var/www/html:ro
      - ./php-fpm/entrypoint.sh:/entrypoint.sh:ro
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./logs/php-fpm:/var/log/php-fpm

  database:
    env_file: ./mysql.env
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 2G
        reservations:
          cpus: 0.5
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    image: docker.io/library/mysql:8.0.45-bookworm
    networks:
      db:
    restart: unless-stopped
    secrets:
      - mysql-root
      - mysql-dostdev
    volumes:
      - ./mysql/logging.cnf:/etc/mysql/conf.d/logging.cnf:ro
      - db-data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql

networks:
  api:
  db:
    internal: true

secrets:
  mysql-dostdev:
    file: ./secrets/mysql-dostdev
  mysql-root:
    file: ./secrets/mysql-root

volumes:
  db-data:
