server {
    listen 80;
    server_name docker.dost.edu.az;
    root /var/www/html;

    location / {
      include fastcgi_params;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_pass application:9000;
    }
}

